import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { mkdtemp, readdir, rmdir, stat, statfs } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { setImmediate as nextTurn } from "node:timers/promises";
import test from "node:test";
import {
  EphemeralEncryptedTemporaryImagingStore,
  TEMPORARY_IMAGING_LIMITS,
} from "../../services/api/dist/imaging-storage/application/ephemeral-encrypted-temporary-imaging-store.js";
import {
  buildSourceIntegrityCapture,
} from "../../services/api/dist/integrity/application/source-integrity-manifest.builder.js";

// Explicit workload command, deliberately outside npm run test:api.
// Generated bytes are not clinically meaningful or DICOM-format fixtures.
// beginPackage is the isolated primitive entry point, NOT a DB quota bypass
// for production. No network, DB, runtime provider or destination is involved.
test("STAGE-009-MAX-001: actual 2 GiB / 2000-object encrypted workload", {
  timeout: 47 * 60_000,
}, async (t) => {
  const MiB = 1024 * 1024;
  const totalBytes = 2048 * MiB;
  const objectCount = 2000;
  const largestObject = 64 * MiB;
  const chunkSize = 64 * 1024;
  const zeroChunk = Buffer.alloc(chunkSize);
  const metrics = {
    sourceBytes: 0, ciphertextBytes: 0, authenticatedBytes: 0,
    sourceChunks: 0, maxSourceChunkBytes: 0,
    maxActiveSources: 0, maxActiveWrites: 0,
    maxConsumerBuffers: 0, maxConsumerBufferBytes: 0,
    peakRssBytes: 0, peakArrayBufferBytes: 0,
    writePauses: 0, consumerPauses: 0,
    captureMilliseconds: 0, postCaptureMilliseconds: 0,
  };
  let stage = "FREE_SPACE";
  let root;
  let storageRoot;
  let store;
  let handle;
  let activeSources = 0;
  let activeWrites = 0;
  let consumerBuffers = 0;
  let writes = 0;
  let cleanupComplete = false;
  const startedAt = performance.now();
  let phaseSignal = AbortSignal.any([t.signal, AbortSignal.timeout(30 * 60_000)]);
  const packageBinding = {
    tenantId: randomUUID(), exchangeSessionId: randomUUID(),
    packageId: randomUUID(), purpose: "PACS_IMPORT",
  };
  const studyRefId = randomUUID();
  const sampleMemory = () => {
    const usage = process.memoryUsage();
    metrics.peakRssBytes = Math.max(metrics.peakRssBytes, usage.rss);
    metrics.peakArrayBufferBytes = Math.max(metrics.peakArrayBufferBytes, usage.arrayBuffers);
    assert.ok(usage.arrayBuffers < 512 * MiB, "ARRAY_BUFFER_SAFETY_BOUND");
    assert.ok(!phaseSignal.aborted, "WORKLOAD_PHASE_DEADLINE_OR_CANCELLED");
  };

  try {
    const capacity = await statfs(tmpdir());
    assert.ok(capacity.bavail * capacity.bsize >= 4096 * MiB, "INSUFFICIENT_TEST_SPACE");
    assert.equal(TEMPORARY_IMAGING_LIMITS.maximumPackageBytes, totalBytes);
    assert.equal(TEMPORARY_IMAGING_LIMITS.maximumInstanceBytes, largestObject);
    assert.equal(TEMPORARY_IMAGING_LIMITS.maximumInstancesPerPackage, objectCount);
    root = await mkdtemp(join(tmpdir(), "mediq-max-study-"));
    storageRoot = join(root, "ciphertext");
    store = new EphemeralEncryptedTemporaryImagingStore({
      rootDirectory: storageRoot,
      ciphertextIo: {
        async write(fileHandle, buffer, offset, length, position) {
          activeWrites += 1;
          metrics.maxActiveWrites = Math.max(metrics.maxActiveWrites, activeWrites);
          try {
            if (++writes % 1024 === 0) {
              metrics.writePauses += 1;
              await nextTurn();
            }
            return await fileHandle.write(buffer, offset, length, position);
          } finally { activeWrites -= 1; }
        },
        sync: (fileHandle) => fileHandle.sync(),
      },
    });
    handle = await store.beginPackage(packageBinding);
    const remaining = totalBytes - largestObject;
    const baseSize = Math.floor(remaining / (objectCount - 1));
    const remainder = remaining % (objectCount - 1);
    const receipts = new Map();
    const sourceDigests = new Map();
    const instances = Array.from({ length: objectCount }, (_, index) => {
      const length = index === 0 ? largestObject : baseSize + (index <= remainder ? 1 : 0);
      const sopInstanceUid = `2.25.${index + 1}`;
      const instanceBinding = { studyRefId, seriesInstanceUid: "2.25.10000", sopInstanceUid };
      return {
        sopInstanceUid,
        async openStream() {
          assert.equal(activeSources, 0, "PREVIOUS_SOURCE_NOT_CLOSED");
          activeSources += 1;
          metrics.maxActiveSources = Math.max(metrics.maxActiveSources, activeSources);
          const writer = await store.beginInstance({
            storageRef: handle.storageRef, packageBinding, instanceBinding,
          });
          let emitted = 0;
          let closed = false;
          const expectedHash = createHash("sha256");
          const closeSource = () => {
            if (!closed) { closed = true; activeSources -= 1; }
          };
          return {
            sopInstanceUid, mediaType: "application/dicom", contentLength: length,
            body: new ReadableStream({
              pull(controller) {
                assert.equal(activeWrites, 0, "SOURCE_PULLED_DURING_CIPHERTEXT_WRITE");
                if (emitted === length) {
                  closeSource();
                  sourceDigests.set(sopInstanceUid, `sha256:${expectedHash.digest("hex")}`);
                  controller.close();
                  return;
                }
                const bytes = Buffer.alloc(Math.min(chunkSize, length - emitted), index % 251);
                expectedHash.update(bytes);
                emitted += bytes.byteLength;
                metrics.sourceBytes += bytes.byteLength;
                metrics.sourceChunks += 1;
                metrics.maxSourceChunkBytes = Math.max(metrics.maxSourceChunkBytes, bytes.byteLength);
                if (metrics.sourceChunks % 64 === 0) sampleMemory();
                controller.enqueue(bytes);
              },
              cancel: closeSource,
            }, { highWaterMark: 0 }),
            observer: {
              writeChunk: (bytes) => writer.write(bytes),
              async complete(expected) {
                assert.ok(expected.sha256 === sourceDigests.get(sopInstanceUid), "SOURCE_DIGEST_MISMATCH");
                const receipt = await writer.complete(expected);
                receipts.set(sopInstanceUid, { receipt, instanceBinding });
                if (receipts.size % 500 === 0) {
                  process.stdout.write(`max_study_progress=STAGING objects=${receipts.size}\n`);
                }
              },
              abort: () => writer.abort(),
            },
          };
        },
      };
    });

    stage = "SOURCE_AND_ENCRYPTION";
    sampleMemory();
    const capture = await buildSourceIntegrityCapture({
      expectedInstanceCount: objectCount, instances, signal: phaseSignal,
    });
    const sealed = await store.sealPackage({ storageRef: handle.storageRef, binding: packageBinding });
    assert.equal(capture.manifest.totalBytes, totalBytes);
    assert.equal(capture.manifest.objectCount, objectCount);
    assert.equal(sealed.totalBytes, totalBytes);
    assert.equal(sealed.objectCount, objectCount);
    assert.equal(receipts.size, objectCount);
    assert.equal(activeSources, 0);
    assert.equal(activeWrites, 0);
    assert.ok(!phaseSignal.aborted, "SOURCE_PHASE_DEADLINE");
    metrics.captureMilliseconds = Math.round(performance.now() - startedAt);
    phaseSignal = AbortSignal.any([t.signal, AbortSignal.timeout(15 * 60_000)]);
    t.diagnostic("max_study_staging=PASS bytes=2147483648 objects=2000");

    stage = "CIPHERTEXT_INVENTORY";
    const directory = join(storageRoot, handle.storageRef);
    const files = await readdir(directory);
    assert.equal(files.length, objectCount);
    for (const { receipt } of receipts.values()) {
      assert.ok(files.includes(`${receipt.objectRef}.enc`), "CIPHERTEXT_OBJECT_MISSING");
      const info = await stat(join(directory, `${receipt.objectRef}.enc`));
      assert.ok(info.isFile(), "CIPHERTEXT_NOT_FILE");
      assert.equal(info.size, receipt.byteLength);
      metrics.ciphertextBytes += info.size;
    }
    assert.equal(metrics.ciphertextBytes, totalBytes);

    stage = "AUTHENTICATED_READ_AND_CONSUMER";
    for (const [index, evidence] of capture.instances.entries()) {
      assert.equal(consumerBuffers, 0, "PREVIOUS_CONSUMER_NOT_RELEASED");
      const { receipt, instanceBinding } = receipts.get(evidence.sopInstanceUid);
      let borrowed;
      await store.consumeInstance({
        storageRef: handle.storageRef, objectRef: receipt.objectRef,
        packageBinding, instanceBinding,
        expectedByteLength: evidence.byteLength, expectedSha256: evidence.sha256,
        signal: phaseSignal,
      }, async () => {
        // Isolated synthetic workload only; no runtime Authorization claim.
        assert.ok(!phaseSignal.aborted, "WORKLOAD_PHASE_DEADLINE_OR_CANCELLED");
        return "VERIFIED";
      }, async (plaintext) => {
        borrowed = plaintext;
        consumerBuffers += 1;
        metrics.maxConsumerBuffers = Math.max(metrics.maxConsumerBuffers, consumerBuffers);
        metrics.maxConsumerBufferBytes = Math.max(metrics.maxConsumerBufferBytes, plaintext.byteLength);
        sampleMemory();
        assert.ok(`sha256:${createHash("sha256").update(plaintext).digest("hex")}` === sourceDigests.get(evidence.sopInstanceUid), "READBACK_DIGEST_MISMATCH");
        assert.equal(plaintext.byteLength, evidence.byteLength);
        if (index % 100 === 0) {
          metrics.consumerPauses += 1;
          await nextTurn();
        }
        metrics.authenticatedBytes += plaintext.byteLength;
      });
      try {
        for (let offset = 0; offset < borrowed.byteLength; offset += chunkSize) {
          const part = borrowed.subarray(offset, Math.min(offset + chunkSize, borrowed.byteLength));
          assert.ok(part.equals(zeroChunk.subarray(0, part.byteLength)), "BORROWED_BUFFER_NOT_ZEROED");
        }
      } finally {
        borrowed = undefined;
        consumerBuffers -= 1;
      }
    }
    assert.equal(metrics.sourceBytes, totalBytes);
    assert.equal(metrics.authenticatedBytes, totalBytes);
    assert.equal(metrics.maxActiveSources, 1);
    assert.equal(metrics.maxActiveWrites, 1);
    assert.equal(metrics.maxSourceChunkBytes, chunkSize);
    assert.equal(metrics.maxConsumerBuffers, 1);
    assert.equal(metrics.maxConsumerBufferBytes, largestObject);
    assert.ok(metrics.writePauses > 0 && metrics.consumerPauses > 0, "SLOW_SINK_NOT_EXERCISED");
    sampleMemory();
    metrics.postCaptureMilliseconds = Math.round(performance.now() - startedAt) - metrics.captureMilliseconds;
  } catch {
    // Never include raw filesystem paths, object references or payload/digests.
    throw new Error(`MAX_STUDY_PROBE_FAILED stage=${stage}`);
  } finally {
    try {
      if (handle) await store.purgePackage({ storageRef: handle.storageRef, binding: packageBinding });
      if (storageRoot) {
        assert.equal((await readdir(storageRoot)).length, 0, "CIPHERTEXT_REMAINS");
        await rmdir(storageRoot);
      }
      if (root) await rmdir(root); // Empty unique directory only, never recursive.
      cleanupComplete = true;
    } catch {
      throw new Error("MAX_STUDY_CLEANUP_FAILED");
    }
  }
  assert.ok(cleanupComplete);
  t.diagnostic(JSON.stringify({
    stage009_maximum_workload: "PASS", scope: "local_synthetic_primitive_only",
    ...metrics, elapsedMilliseconds: Math.round(performance.now() - startedAt), cleanup: "PASS",
    db_and_pacs: "NOT_ACCESSED", full_stage009: "NOT_PROVEN",
  }));
});
